export enum DATA_TYPE {
  COUNTER = "counter",
  RESET = "reset",
  RANGE = "range",
  OPTION = "option",
  AUTO_COUNTER = "autoCounter",
  START_AT_ZERO = "stopAtZero",
  CUSTOM_STOP = "customStop",
  AUTO_COUNTER_TYPE = "autoCounterType",
  DEFAULT_COUNTER = "defaultCounter",
}

export enum STORE {
  STORE_DATA = "store"
}

export const TYPE = {
  DATA: {
    COUNTER: DATA_TYPE.COUNTER,
    RESET: DATA_TYPE.RESET,
    RANGE: DATA_TYPE.RANGE,
    OPTION: DATA_TYPE.OPTION,
    AUTO_COUNTER: DATA_TYPE.AUTO_COUNTER,
    START_AT_ZERO: DATA_TYPE.START_AT_ZERO,
    CUSTOM_STOP: DATA_TYPE.CUSTOM_STOP,
    AUTO_COUNTER_TYPE: DATA_TYPE.AUTO_COUNTER_TYPE,
    DEFAULT_COUNTER: DATA_TYPE.DEFAULT_COUNTER,
  },
  STORE: STORE.STORE_DATA
}
